version: '3.8'
services:
  database:
    container_name: sgps-database
    image: mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: 'sgps-db'
      MYSQL_USER: user
      MYSQL_PASSWORD: root
    volumes:
      - ./docker/mysql:/var/lib/mysql
    restart: on-failure
    networks:
      - sgps-network
networks:
  sgps-network:
    name: sgps-network
    driver: bridge
